#!/bin/bash
if [ "$1" = "compile" ]
then
    javac --source-path ./jlox/src ./jlox/src/com/craftinginterpreters/lox/Lox.java
elif [ "$1" = "clean" ]
then
    rm -f ./jlox/src/com/craftinginterpreters/lox/*.class
elif [ "$1" = "repl" ]
then
    java -cp ./jlox/src com/craftinginterpreters/lox/Lox
else
    if [ -z "$1" ]
    then
        echo "Arguments:"
        echo "repl            Run REPL"
        echo "<filename>.lox  Interpret file"
        echo "compile         Compile Lox Java Sources"
        echo "clean           Delete .class files"
    else
        java -cp ./jlox/src com/craftinginterpreters/lox/Lox "$1"
    fi
fi