#!/bin/bash
if [ "$1" = "compile" ]
then
    javac --source-path ./jlox/src ./jlox/src/com/craftinginterpreters/lox/Lox.java
elif [ "$1" = "clean" ]
then
    rm ./jlox/src/com/craftinginterpreters/lox/*.class
elif [ "$1" = "repl" ]
then
    java -cp ./jlox/src com/craftinginterpreters/lox/Lox
elif [ "$1" = "interpret" ]
then
    if [ -z "$2" ]
    then
        echo "Specify a file to interpret."
    else
        java -cp ./jlox/src com/craftinginterpreters/lox/Lox "$2"
    fi
fi