#!/bin/bash
if [ "$1" = "compile" ]
then
    javac --source-path ./jlox/src ./jlox/src/com/craftinginterpreters/lox/Lox.java
elif [ "$1" = "clean" ]
then
    rm ./jlox/src/com/craftinginterpreters/lox/*.class
elif [ "$1" = "repl" ]
then
    java -cp ./jlox/src com/craftinginterpreters/lox/Lox
elif [ "$1" = "interpret" ]
then
    java -cp ./jlox/src com/craftinginterpreters/lox/Lox demo.lox
fi